apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummy-strategy
  namespace: trading-apps
spec:
  rules:
  - host: dummy-strategy.trading.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dummy-strategy
            port:
              number: 8000
