apiVersion: v1
kind: Service
metadata:
  name: dummy-strategy
  namespace: trading-apps
spec:
  selector:
    app: dummy-strategy
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP
