apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alpaca-ingestion
  - dummy-strategy

commonLabels:
  app.kubernetes.io/part-of: trading-system
  app.kubernetes.io/managed-by: kustomize
