apiVersion: v1
kind: Service
metadata:
  name: alpaca-ingestion
  namespace: trading-apps
spec:
  selector:
    app: alpaca-ingestion
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP
