apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - ../../../base/kafka
  - topics/stock-ticks.yaml
  - topics/trade-signals.yaml

commonLabels:
  environment: dev

patches:
  - path: patches.yaml
