apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - kafka-metrics-config.yaml
  - kafka-cluster.yaml
  - users/trading-app-user.yaml

commonLabels:
  app.kubernetes.io/part-of: trading-system
  app.kubernetes.io/managed-by: kustomize
