apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trading-apps

resources:
  - ../../../base/apps/dummy-strategy

commonLabels:
  environment: dev

patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
